import 'package:foodapp/constants/assets.dart';
import 'package:foodapp/data_layer/data_base/global_demo_data_model.dart';
import 'package:foodapp/data_layer/data_models/random_data.dart';

// ${Assets.fastBase}1.jpg
List<FoodModel> fastFoodDemoData = [
  FoodModel(
    foodType: "FastFood",
    foodName: "WAFFLE FRIES",
    imagePath: "${Assets.fastBase}1.jpg",
    calories: RandomData.getRandomCalories,
    description:
        "You know the scene in Scott Pilgrim vs. the World where Scott tells Ramona that, were he to have his way, he'd eat garlic bread forever without ever having to stop? I could probably do that with Chick-fil-A waffle fries. Except then I'd get fat. Fries make you fat.",
    foodPrice: 22.99,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "DOUBLE-DOUBLE",
    imagePath: "${Assets.fastBase}2.jpg",
    description:
        "There's one small change that can take the Double-Double from “best burger ever” to “literal perfection between two buns.” Ask for grilled onions—instead of the sliced onion—the next time you order one. It gets you halfway to Animal Style for free.",
    calories: RandomData.getRandomCalories,
    foodPrice: 32.09,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "FRIES MCDONALD'S",
    imagePath: "${Assets.fastBase}3.jpg",
    description:
        " There is a semi-fancy bar that my friends and I like to go to, and we always order a big bowl of their fries because they taste like McDonald's fries. No matter how fancy the restaurant, “Tastes like McDonald's fries” is the highest compliment you can give a french fry. Also, no other fast-food item has a Kanye West poem written about it. “I don't trust no food that smells that good, man,” he says of the fries in “McDonald's Man.” There is no competition; this is the most foolish thing Kanye West has ever said.",
    calories: RandomData.getRandomCalories,
    foodPrice: 22.99,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "CHICKEN POPEYES",
    imagePath: "${Assets.fastBase}4.jpg",
    description:
        "The only bad thing about Beyoncé is that she has a lifetime of free chicken at Popeyes but, being a vegan, can't take advantage of it. Imagine having unfettered access to that succulent meat and those perfectly crisp and savory flaps of fried skin every day.",
    calories: RandomData.getRandomCalories,
    foodPrice: 32.09,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: " CHICKEN SANDWICH",
    imagePath: "${Assets.fastBase}5.jpg",
    description:
        "The Chick-fil-A chicken sandwich is transcendent. The perfect combination of a generous portion of breaded chicken, soft bun, and tart pickles, it's enhanced by only one thing: Polynesian sauce.",
    calories: RandomData.getRandomCalories,
    foodPrice: 13.84,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "CURLY FRIES ARBY'S",
    imagePath: "${Assets.fastBase}6.jpg",
    description:
        " Picture some of the best things in life: grandiose spiral staircases; chocolate-vanilla swirl ice cream cones; Slinkies descending slowly down steps. What do they all have in common? Their shape. Apply that same shape to salted, deep-fried potatoes, and of course you'd end up with perfection in physical form: Arby's curly fries.",
    calories: RandomData.getRandomCalories,
    foodPrice: 13.84,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "Ice-Cream choclote",
    imagePath: "${Assets.fastBase}7.jpg",
    description:
        "Tagliatelle ai funghi is a flavorful Italian dish consisting of fresh tagliatelle pasta paired with meaty mushrooms such as porcini (the most common choice), portobello, or chanterelles",
    calories: RandomData.getRandomCalories,
    foodPrice: 23.12,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: " BLIZZARD DAIRY QUEEN",
    imagePath: "${Assets.fastBase}8.jpg",
    description:
        "To come to terms with your existence in a capitalist society is to accept that nothing is good, fast, and cheap. Well, almost nothing. You can have two, but not all three—unless you buy a Frosty.",
    calories: RandomData.getRandomCalories,
    foodPrice: 23.00,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "MCFLURRY MCDONALD'S",
    imagePath: "${Assets.fastBase}9.jpg",
    description:
        "If the DQ Blizzard is the winter storm warning of frozen desserts, the McDonald's McFlurry is made of the gently falling flakes that turn your world into a beautiful snow globe. There's no better end to a McD's feast than M&M's or Oreos cascading through creamy soft serve (or at least through the upper third of the cup ... it's not a perfect system, OK?). Plus, the spoon is a marvel of modern utensil technology.",
    calories: RandomData.getRandomCalories,
    foodPrice: 23.74,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "BACON CHEESEBURGER ",
    imagePath: "${Assets.fastBase}10.jpg",
    description:
        "Bacon cheeseburgers are great because beef is great, cheese is great, and bacon is great, and these things are all great together. But most fast-food hamburgers taste vaguely savory, seem to be made of ingredients that are only food-like, and have the texture of sludge once they're in your mouth. The burger at Five Guys tastes like an actual bacon cheeseburger made with beef and bacon, and that's why it's good. This isn't complicated.",
    calories: RandomData.getRandomCalories,
    foodPrice: 43.87,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "ANIMAL STYLE BURGER ",
    imagePath: "${Assets.fastBase}11.jpg",
    description:
        "What does Southern California taste like? A bunch of things: salty air at the beach. Smog. But mostly a burger, griddled, topped with something like Thousand Island dressing and tiny grilled onions. Best eaten in the car.",
    calories: RandomData.getRandomCalories,
    foodPrice: 35.87,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "SPICY CHICKEN SANDWICH",
    imagePath: "${Assets.fastBase}12.jpg",
    description:
        "The Chick-fil-A spicy chicken sandwich is iconic, and it isn't even a decade old. Believe it or not, the spicy option was first introduced in 2010. It took more than 50 years to arrive, but there's joy in knowing they got it right. Strip away the promotional gimmicks from its competitors and you'll find that Chick-fil-A has the best, spiciest chicken sandwich in all of fast food.",
    calories: RandomData.getRandomCalories,
    foodPrice: 24.75,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "CHICKEN NUGGETS",
    imagePath: "${Assets.fastBase}13.jpg",
    description:
        "I grew up in Atlanta, Georgia, where the mark of a good party was a Chick-fil-A nugget platter on the coffee table. The humble Chick-fil-A nugget is the best portable chicken product on the market, and it is still a reliable indicator of whether a social gathering is worth your time. As Martha Stewart once said, “No nuggets, no party.” Believe her.",
    calories: RandomData.getRandomCalories,
    foodPrice: 13.84,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "MCNUGGETS ",
    imagePath: "${Assets.fastBase}14.jpg",
    description:
        "There are only a few things in life that are certain: death, taxes, an episode of Law & Order being on right now, and Chicken McNuggets being delicious. Whether it's the one shaped like a boot, or the oval McNugget that has the purple, rubber-band–like vein, they are the perfect food. I'd get into how incredible the breading on a McNugget is, but words can't do it justice.",
    calories: RandomData.getRandomCalories,
    foodPrice: 23.22,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "CHEESY GORDITA CRUNCH ",
    imagePath: "${Assets.fastBase}15.jpg",
    description:
        " An effective fast-food experience hinges on texture. Mouthfeel. Most fast food is rough and salty or mushy and gelatinous. But rarely the twain shall meet in one package. Except, of course, for the double-tortilla, hard-soft, cheesy, beefy, sturdy, peerless Cheesy Gordita Crunch, Taco Bell's perennial off-menu, on-point secret weapon.",
    calories: RandomData.getRandomCalories,
    foodPrice: 23.92,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "BIG MAC",
    imagePath: "${Assets.fastBase}16.jpg",
    description:
        "What does it take to really make a relationship work? Love, of course. Compassion. Trust. Sesame seed buns. Kindness. Two hamburgers. Understanding. A special sauce. Pickles. Onions. Cheese. Lettuce. Big Macs forever, man.",
    calories: RandomData.getRandomCalories,
    foodPrice: 87.6,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "PRETZEL ",
    imagePath: "${Assets.fastBase}17.jpg",
    description:
        "Auntie Anne's services all tastes and cravings with perfectly proportioned bites of doughy deliciousness. Want sweet but messy? Try the cinnamon sugar. Want flavored but smelly? Buy the garlic parmesan. And for the simple pretzel connoisseur, the original “built an empire,” the shop's menu says. Count me as a satisfied, snacking citizen.",
    calories: RandomData.getRandomCalories,
    foodPrice: 21.84,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "SHACK BURGER ",
    imagePath: "${Assets.fastBase}18.jpg",
    description:
        "The Shake Shack ShackBurger is perfect. It's simple, yet high quality. From the bun to the sauce, you can't eat one without feeling satisfied. For those that say it's not fast food, it started out as a food cart. That's about as fast and basic as you can make food.",
    calories: RandomData.getRandomCalories,
    foodPrice: 13.84,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "TWO TACOS",
    imagePath: "${Assets.fastBase}19.jpg",
    description:
        "Where to start? How about that no other fast-food item is known for having its price in the title—because it's THAT good. You could feed yourself for a week for like \$10 with these tacos. Next there's the quantity, which happens to be TWO. I don't need to sell you on the number two—the gods Marvin Gaye and Kim Weston have done that for us. Lastly, and this is key, we're talking about tacos. Find someone who doesn't like a greasy, mysterious, delicious taco, and you've found yourself Beelzebub incarnate.",
    calories: RandomData.getRandomCalories,
    foodPrice: 33.74,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "SPICY CHICKEN SANDWICH",
    imagePath: "${Assets.fastBase}20.jpg",
    description:
        "Wendy's spicy chicken sandwich is the Larry Fitzgerald of fast-food items: It's no longer the newest or most exciting option out there, but it's a surefire Hall of Famer. The meat is thick and juicy, it's perfectly seasoned,  and it consistently produces— make no mistake, it can still single-handedly win you a meal",
    calories: RandomData.getRandomCalories,
    foodPrice: 28.07,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "CHICKEN TENDERS",
    imagePath: "${Assets.fastBase}21.jpg",
    description:
        "Popeyes chicken tenders are an extremely satisfying meal, and not just because their airy, crispy coating packs such a perfect crunch. Their long, thin shape is precisely engineered for optimal dipping into those tiny tubs of Bayou Buffalo or Blackened Ranch, making for a spicy and delicious synergy between finger food and condiment.",
    calories: RandomData.getRandomCalories,
    foodPrice: 27.09,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "BISCUITS ",
    imagePath: "${Assets.fastBase}22.jpg",
    description:
        " The Popeyes biscuit isn't the best part of a Popeyes meal, but it is absolutely essential—the ideal buttery companion for your juicy, spicy chicken; the delicious spoon for your mashed potatoes and gravy. Don't let the way the biscuit is haphazardly tossed in the bottom of your box fool you: It is an integral part of the best meal fast food has to offer.",
    calories: RandomData.getRandomCalories,
    foodPrice: 27.09,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "SOFT TACOS",
    imagePath: "${Assets.fastBase}23.jpg",
    description:
        "Everything at Chipotle is pretty good and the soft tacos are good because it's Chipotle.",
    calories: RandomData.getRandomCalories,
    foodPrice: 37.09,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: " ANIMAL STYLE FRIES",
    imagePath: "${Assets.fastBase}24.jpg",
    description:
        "In-N-Out's fries are just fine. Nothing special. But order them “Animal Style” from the not-so-secret secret menu and get them doused in sauce, drenched in cheese, and sprinkled with caramelized onions. Then grab a fork or get your hands dirty. The ordinary is now decadent, and it's a delicious mess.",
    calories: RandomData.getRandomCalories,
    foodPrice: 22.87,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "CRUNCHY SHELL TACOS",
    imagePath: "${Assets.fastBase}25.jpg",
    description:
        "Taco Bell crunchy tacos are perfect drunk food and hangover food: The crispy shell distracts from what some say is gooey meat (I say delicious!) for maximum late-night consumption, and there's some sort of magic preservative in them that keeps the shell just crunchy enough for day-after eating. Separate, the ingredients are nothing: tasteless iceberg lettuce, mediocre shredded cheese, questionable meat, and a fried tortilla. Together, they are perfect.",
    calories: RandomData.getRandomCalories,
    foodPrice: 43.87,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "CAJUN FRIES",
    imagePath: "${Assets.fastBase}26.jpg",
    description:
        "Five Guys fries are the only fast-food item that give you the smug, farm-to-table satisfaction of knowing exactly where your (technical) vegetables are sourced. They are generously portioned; the proper serving size is “one full paper bag.” And thanks to that highly addictive seasoning, they are delicious.",
    calories: RandomData.getRandomCalories,
    foodPrice: 22.87,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "DOUBLE SHACKBURGER",
    imagePath: "${Assets.fastBase}27.jpg",
    description:
        "Comparing the Double ShackBurger to In-N-Out's Double-Double is like comparing a Tesla Model S to a Honda Civic. While the Civic is an affordable and reliable car, the Model S is more elegant and refined. It's double the price—and double the quality.",
    calories: RandomData.getRandomCalories,
    foodPrice: 43.87,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "BAKED APPLE PIE",
    imagePath: "${Assets.fastBase}28.jpg",
    description:
        " I have written at length about my intense admiration for the McDonald's apple pie, a.k.a. mankind's most perfect creation, in the past. To sum it up: (1) sweet, (2) not too sweet, (3) filling, (4) not too filling, (5) SOLD IN FREAKING PAIRS. There are many great fast foods, but the Golden Arches' twin dessert is the greatest of them all.",
    calories: RandomData.getRandomCalories,
    foodPrice: 55.04,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "HASH BROWNS ",
    imagePath: "${Assets.fastBase}29.jpg",
    description:
        "You know how in dystopian sci-fi, everyone eats bland Food Units in the future? The McD's hash browns are like that: a perfectly crispy, offensively salty block of pure beige wonder.",
    calories: RandomData.getRandomCalories,
    foodPrice: 23.75,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "CHICKEN BISCUIT",
    imagePath: "${Assets.fastBase}30.jpg",
    description:
        "There are no greater biscuits. It's flaky buttermilk goodness baked to a golden brown. It's crunchy enough to distinguish itself from a dinner roll without being a wheat-based brick. It's salty enough to be perfectly accented by a cup of sugary lemonade, maximizing caloric euphoria. The day this becomes an all-day breakfast item is the day I reevaluate my life insurance.",
    calories: RandomData.getRandomCalories,
    foodPrice: 22.87,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "STEAKBURGER ",
    imagePath: "${Assets.fastBase}31.jpg",
    description:
        "The Steakburger is the Double-Double without all the hype. It's a great blend of taste and convenience, and it's exactly what you should be looking for when it comes to a fast-food hamburger.",
    calories: RandomData.getRandomCalories,
    foodPrice: 43.87,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "EGG MCMUFFIN",
    imagePath: "${Assets.fastBase}32.jpg",
    description:
        "The McDonald's Egg McMuffin hides a quiet sophistication; its mass-market prominence as a staple of an enormous conglomerate belies the fusion of three countries' cultural and culinary heritages, combining a fluffy, buttery English muffin, a crispy slice of Canadian bacon, and a melty, decadent slice of American cheese. And also an egg. It's delicious whether you're in London, Vancouver, or New York",
    calories: RandomData.getRandomCalories,
    foodPrice: 43.87,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "ROAST BEEF SANDWICH",
    imagePath: "${Assets.fastBase}33.jpg",
    description:
        "If you don't like the roast beef sandwich at Arby's, chances are you haven't tried it. With the perfect grease-to-beef ratio at 90-10, your tastebuds will thank you.",
    calories: RandomData.getRandomCalories,
    foodPrice: 32.09,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "CHICKEN FINGERS",
    imagePath: "${Assets.fastBase}34.jpg",
    description:
        "The only thing wrong with Raising Cane's is its limited regional availability. The tenders feature the perfect balance of seasoned, crunchy breading and tender, juicy chicken. Forget that “signature blend of herbs and spices”—these tenders put the Colonel's chicken to shame.",
    calories: RandomData.getRandomCalories,
    foodPrice: 12.21,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "CHEESEBURGER ",
    imagePath: "${Assets.fastBase}35.jpg",
    description:
        "I once had to drive from Fort Collins, Colorado, to Santa Cruz, California—a journey of roughly 20 hours—alone in a car with no radio. For the journey, I bought two CDs—Yoshimi Battles the Pink Robots by the Flaming Lips and Original Pirate Material by the Streets—and four tall cans of Rockstar Energy drink. Somewhere west of the Great Salt Lake, I pulled over at a rest stop that looked like it was the site of roughly 50 grisly sex-murders. ",
    calories: RandomData.getRandomCalories,
    foodPrice: 22.98,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "CHICKEN QUESADILLA",
    imagePath: "${Assets.fastBase}36.jpg",
    description:
        "Go to the Google search bar and start typing “What is the sauce in the”—then let it hang. The very first suggestion is “Taco Bell quesadilla,” a cheesy creation with a tangy yet spicy sauce. Being the top result on a Google search is an anonymous consensus: This quesadilla is special.",
    calories: RandomData.getRandomCalories,
    foodPrice: 10.34,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "HONEY BBQ CHICKEN SANDWICH",
    imagePath: "${Assets.fastBase}37.jpg",
    description:
        "It's the James Harden of fast-food sandwiches. The dynamic blend of flavors and textures makes for a sublime experience. It's so damn good the nutrition label doesn't matter, much like Harden's defense.",
    calories: RandomData.getRandomCalories,
    foodPrice: 43.32,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "CHERRY LIMEADE",
    imagePath: "${Assets.fastBase}38.jpg",
    description:
        "(1) Limeade is the greatest beverage, if not engineering achievement of any kind, in human history. (2) Sonic cherry limeade is not limeade as such, but with the flirtation of sweet-and-sour between cherry and lime juice, and a hint of carbonation, it's nearly as piquant as the genuine article. (3) Your teeth and pancreas might not thank you for mainlining Sonic cherry limeade, but we think with our brains and feel with our hearts, and our teeth and pancreases can shut the hell up.",
    calories: RandomData.getRandomCalories,
    foodPrice: 23.99,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "SOFT COOKIES",
    imagePath: "${Assets.fastBase}39.jpg",
    description:
        "The soft cookies at Subway are often overlooked, presumably because the stench of the bread overwhelms, but they are consistently delicious with just the right density and temperature.",
    calories: RandomData.getRandomCalories,
    foodPrice: 37.76,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "GLAZED DOUGHNUT",
    imagePath: "${Assets.fastBase}40.jpg",
    description:
        "One of the first programs I ever watched on an HDTV was the Krispy Kreme Challenge, an annual race in Raleigh, North Carolina, where contestants eat a dozen glazed doughnuts and then run 2.5 miles. I watched runners puking up sugary dough in startling high definition. But my primary thought remained, “I could really go for a glazed doughnut right now.” That's how good they are.",
    calories: RandomData.getRandomCalories,
    foodPrice: 22.3,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: " SPICY CHICKEN DELUXE SANDWICH",
    imagePath: "${Assets.fastBase}41.jpg",
    description:
        "Someone took a tender, juicy, and perfectly fried piece of chicken and made it easier to eat by sticking it on a sandwich (and adding cheese)! Add some Polynesian, ranch, or Chick-fil-A sauce if you like, but frankly, this sandwich is so simple and perfect and delicious that it must be a sin to eat it. That's why you can't get them on Sundays.",
    calories: RandomData.getRandomCalories,
    foodPrice: 61.2,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "MCGRIDDLE ",
    imagePath: "${Assets.fastBase}42.jpg",
    description:
        "In the culinary world, there are few instances where salty meets sweet in order to form a union so perfect, it would make the forefathers jealous. By packing breakfast staples like sausage, egg, cheese, and syrup-infused pancakes into a handheld device, the McGriddle is America's oversimplistic response to the morning dilemma of “I want all the breakfast food” and “I have no time.” It's as patriotic as it is perfect.",
    calories: RandomData.getRandomCalories,
    foodPrice: 26.62,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "ORIGINAL CHICKEN SANDWICH",
    imagePath: "${Assets.fastBase}43.jpg",
    description:
        "It's juicy and has just the right amount of zesty flavor—it's like a flattened, elongated chicken nugget. Most importantly—the mayonnaise. Burger King is not afraid to liberally spread mayo on both sides of the long bun. I'm guessing it's like three tablespoons worth of sweet, sweet mayo. My scientific theory: The almost excessive amount of mayonnaise not only adds an extra dose of umami, but also acts as some sort of flavor sealant. I don't see a Chick-fil-A offering such scientific advances, that's all I'm saying.",
    calories: RandomData.getRandomCalories,
    foodPrice: 33.22,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "FILET-O-FISH",
    imagePath: "${Assets.fastBase}44.jpg",
    description:
        "McDonald's hamburgers are good for what they are: flat salt pouches filled with sagging vegetables and too much goddamn ketchup. The Filet-O-Fish dispenses with the ketchup problem altogether and instead offers an ostensibly strange and ill-advised, but practically indispensable, combination of square laboratory fish and American cheese, flaky and buttery and fun. (The McGriddle is fun but impractical, layers-wise.) It is by far the best off-burger McDonald's sandwich, and burgers are overrated anyway.",
    calories: RandomData.getRandomCalories,
    foodPrice: 12.22,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "MASHED POTATOS AND CAJUN GRAVY",
    imagePath: "${Assets.fastBase}45.jpg",
    description:
        "You can (and should!) make an entire meal out of Popeyes' signature sides, but if you feel compelled to cap your intake at one, opt for the mashed potatoes with cajun gravy. The potatoes, while smooth and creamy, are merely the vehicle for the true star: a rich, tangy, and hearty gravy that's so sumptuous you'll be tempted to ladle it into your mouth like soup. Ask for extra so that you can do just that.",
    calories: RandomData.getRandomCalories,
    foodPrice: 31.87,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "WHOPPER ",
    imagePath: "${Assets.fastBase}46.jpg",
    description:
        "The contributing factors to the success of BK's signature burger are uncomplicated: catchy name (very important), tasty accoutrements (crunchy onions, ridged pickles), perfect condiments (ketchup, mayo), appropriate size (wide and flat yet substantive), and of course, that trademark “flame-broiled”—sorry, “fire-grilled”—flavor. Plus, it's Bruce Lee's favorite burger.",
    calories: RandomData.getRandomCalories,
    foodPrice: 43.12,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "CHICKEN ",
    imagePath: "${Assets.fastBase}47.jpg",
    description:
        "Here are three things that make KFC great: (1) If you order in bulk, you will receive your food not in a foil wrapper or a cardboard box, but in a bucket, which is dope. (2) The restaurant’s chicken is so delicious that it was able to survive both a (false) rumor that it rebranded from “Kentucky Fried Chicken” to “KFC” because legally what it was serving was not chicken, and a (fake) viral story that they served someone a fried rat. (3) Its biscuits are fluffy, and buttery enough to stand on their own as a main dish.",
    calories: RandomData.getRandomCalories,
    foodPrice: 9.03,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "CHEESE CURDS",
    imagePath: "${Assets.fastBase}48.jpg",
    description:
        "A major problem with cheese is that it is, in at least its socially acceptable forms, difficult to eat: You need a plate, a knife, a grater, some sort of grain or meat to put it on, etc. The Midwest, God bless it, has eliminated that problem. Culver's knows that man's usual condition—“not enough cheese”—can be easily solved; one visit to a drive-through window and you will be a (kind of oily, but worth it) sack of delicious, deep-fried cheese curds richer. Every fast-food chain should sell cheese curds. We would be a better world.",
    calories: RandomData.getRandomCalories,
    foodPrice: 15.45,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "QUARTER POUNDER",
    imagePath: "${Assets.fastBase}49.jpg",
    description:
        "The McDonald's Quarter Pounder doesn't need a special sauce or its own jingle. It doesn't need to be done “Animal Style.” It is simple Midwestern cholesterol-coated perfection. This low ranking is a disgrace.",
    calories: RandomData.getRandomCalories,
    foodPrice: 52.87,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
  FoodModel(
    foodType: "FastFood",
    foodName: "CHEESEBURGER ",
    imagePath: "${Assets.fastBase}50.jpg",
    description:
        "Five Guys crafts their cheeseburgers, they don't just plain old make them, and yes, there's a difference—in flavor, quality, and number of drips of glorious grease. If your burger doesn't come in a bag so soaked it's transparent, you're doing it wrong, and Five Guys does it very right.",
    calories: RandomData.getRandomCalories,
    foodPrice: 63.09,
    foodRate: RandomData.getRandomRate,
    numberOfReviewers: RandomData.getRandomReviewers,
  ),
];
