import 'package:foodapp/constants/assets.dart';
import 'package:foodapp/data_layer/data_base/global_demo_data_model.dart';
import 'package:foodapp/data_layer/data_models/random_data.dart';

List<FoodModel> globalDishesDemoData = <FoodModel>[
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Butter Garlic Naan",
    description:
        "Butter garlic naan is a traditional Indian flatbread and one of the most popular versions of naan. It's made with flour, yeast, salt, sugar, and yogurt. Once the dough has been baked in a hot tandoor oven, the golden naan is taken out and brushed with butter or ghee, then topped with minced garlic.",
    imagePath:
        "asstes/images/global_dishes/global_dishes_images/Butter-Garlic-Naan.jpg",
    foodPrice: 243.0,
    foodRate: 4.8,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "INDIA",
    dishCountryFlag: "${Assets.flageBase}Inde.svg",
    ingredientsNames: [
      "Flours",
      "Garlic",
      "Yeasts",
      "Salts",
      "Sugars",
      "Yogurt",
      "Ghee",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}5/1-ingredient.png",
      "${Assets.gobalIngBase}5/2-ingredient.png",
      "${Assets.gobalIngBase}5/3-ingredient.png",
      "${Assets.gobalIngBase}5/4-ingredient.png",
      "${Assets.gobalIngBase}5/5-ingredient.png",
      "${Assets.gobalIngBase}5/6-ingredient.png",
      "${Assets.gobalIngBase}5/7-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Pan de bono",
    description:
        "Pan de bono is a traditional Colombian bread consisting of cassava starch, cornmeal or corn flour, queso fresco, eggs, and sugar. The bread is shaped into bagels or balls that are slightly larger than golf balls. Pan de bono is similar to other South American cheese breads like pan de queso, difference being added conr flour or cornmeal, and a hint of sweeteness due to the addition of sugar.",
    imagePath:
        "asstes/images/global_dishes/global_dishes_images/Pan-de-bono.jpg",
    foodPrice: 102.0,
    foodRate: 4.9,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "COLOMBIA",
    dishCountryFlag: "${Assets.flageBase}Colombie.svg",
    ingredientsNames: [
      "Cassava Starch",
      "Costeño",
      "Queso fresco",
      "Eggs",
      "Cornmeals",
      "Corn Flours",
      "Sugars",
      "Salts",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}6/1-ingredient.png",
      "${Assets.gobalIngBase}6/2-ingredient.png",
      "${Assets.gobalIngBase}6/3-ingredient.png",
      "${Assets.gobalIngBase}6/4-ingredient.png",
      "${Assets.gobalIngBase}6/5-ingredient.png",
      "${Assets.gobalIngBase}6/6-ingredient.png",
      "${Assets.gobalIngBase}6/7-ingredient.png",
      "${Assets.gobalIngBase}6/8-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Tonkotsu ramen",
    description:
        "Tonkotsu is a unique style of ramen consisting of an extremely rich, fatty pork broth, fresh noodles, soft-yolk eggs, and tender pork belly that melts in the mouth. It is so popular and special that it could be a dish of its own, not just a ramen style.",
    imagePath:
        "asstes/images/global_dishes/global_dishes_images/Tonkotsu-ramen.jpg",
    foodPrice: 27.0,
    foodRate: 4.3,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "FUKUOKA, JAPAN",
    dishCountryFlag: "${Assets.flageBase}Japon.svg",
    ingredientsNames: [
      "Ramen Noodles",
      "Porks",
      "Stocks",
      "Pork Fats",
      "Eggs",
      "Scallions",
      "Bamboo Shoots",
      "Nori",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}7/1-ingredient.png",
      "${Assets.gobalIngBase}7/2-ingredient.png",
      "${Assets.gobalIngBase}7/3-ingredient.png",
      "${Assets.gobalIngBase}7/4-ingredient.png",
      "${Assets.gobalIngBase}7/5-ingredient.png",
      "${Assets.gobalIngBase}7/6-ingredient.png",
      "${Assets.gobalIngBase}7/7-ingredient.png",
      "${Assets.gobalIngBase}7/8-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Carnitas",
    description:
        "Originating from the Mexican state of Michoacán, carnitas is a flavorful dish made from pork (usually front sections or pork shoulder) that is braised, roasted, or slow-cooked in its own fat for a long time until fully tender and succulent.",
    imagePath: "asstes/images/global_dishes/global_dishes_images/Carnitas.jpg",
    foodPrice: 109.0,
    foodRate: 4.6,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "MICHOACÁN, MEXICO",
    dishCountryFlag: "${Assets.flageBase}Mexique.svg",
    ingredientsNames: [
      "Porks",
      "Lards",
      "Salts",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}8/1-ingredient.png",
      "${Assets.gobalIngBase}8/2-ingredient.png",
      "${Assets.gobalIngBase}8/3-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Châteaubriand",
    description:
        "Contrary to popular belief, the word Châteaubriand does not refer only to a cut of beef, but to a method used to grill or roast a thick cut of beef tenderloin. The steak was originally prepared by a chef named Montmireil in 1822 for a French author, diplomat, and statesman Francois René Vicomte de Chateaubriand.",
    imagePath:
        "asstes/images/global_dishes/global_dishes_images/Châteaubriand.jpg",
    foodPrice: 209.0,
    foodRate: 4.6,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "FRANCE",
    dishCountryFlag: "${Assets.flageBase}France.svg",
    ingredientsNames: [
      "Beef Cattle Breeds",
      "Shallots",
      "Olive Oils",
      "Black Pepper",
      "Salts",
      "Vinegars",
      "Eggs",
      "Butters",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}9/1-ingredient.png",
      "${Assets.gobalIngBase}9/2-ingredient.png",
      "${Assets.gobalIngBase}9/3-ingredient.png",
      "${Assets.gobalIngBase}9/4-ingredient.png",
      "${Assets.gobalIngBase}9/5-ingredient.png",
      "${Assets.gobalIngBase}9/6-ingredient.png",
      "${Assets.gobalIngBase}9/7-ingredient.png",
      "${Assets.gobalIngBase}9/8-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Carne asada tacos",
    description:
        "Carne asada tacos are the first tacos in history. It is believed that the first tacos appeared in the 1500s, made with thin slices of meat cooked over hot coals. The meat was placed in a corn tortilla and topped with guacamole, onions, chili peppers, and lime, also known as the carne asada taco.",
    imagePath:
        "asstes/images/global_dishes/global_dishes_images/Carne-asada-tacos.jpg",
    foodPrice: 134.0,
    foodRate: 4.3,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "MEXICO",
    dishCountryFlag: "${Assets.flageBase}Mexique.svg",
    ingredientsNames: [
      "Tortilla",
      "Beef Cattle Breeds",
      "Guacamole",
      "Salsa verde",
      "Onions",
      "Hot Peppers",
      "Limes",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}10/1-ingredient.png",
      "${Assets.gobalIngBase}10/2-ingredient.png",
      "${Assets.gobalIngBase}10/3-ingredient.png",
      "${Assets.gobalIngBase}10/4-ingredient.png",
      "${Assets.gobalIngBase}10/5-ingredient.png",
      "${Assets.gobalIngBase}10/6-ingredient.png",
      "${Assets.gobalIngBase}10/8-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Khinkali",
    description:
        "These delicious Georgian dumplings known as khinkali are considered to be one of the national dishes of the country. The dumplings are filled with meat and spices, then traditionally twisted into a knot at the top. Regional differences influence the fillings and every part of Georgia has their distinctive variety.",
    imagePath: "asstes/images/global_dishes/global_dishes_images/Khinkali.jpg",
    foodPrice: 342.0,
    foodRate: 4.3,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "GEORGIA",
    dishCountryFlag: "${Assets.flageBase}Georgie.svg",
    ingredientsNames: [
      "Beef Cattle",
      "Lambs",
      "Flours",
      "Salts",
      "Onions",
      "Caraway",
      "Coriander",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}11/1-ingredient.png",
      "${Assets.gobalIngBase}11/2-ingredient.png",
      "${Assets.gobalIngBase}11/3-ingredient.png",
      "${Assets.gobalIngBase}11/4-ingredient.png",
      "${Assets.gobalIngBase}11/5-ingredient.png",
      "${Assets.gobalIngBase}11/6-ingredient.png",
      "${Assets.gobalIngBase}11/7-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Pernil",
    description:
        "Pernil is one of Puerto Rico's most famous dishes, a succulent roasted pork shoulder that is traditionally seasoned in a marinade called adobo mojado, consisting of paprika, salt, vinegar, garlic, and oregano. The name of the dish is derived from the Spanish word pierna, meaning leg, but it is also a Catalan word for ham, referring to the traditional recipe that calls for fresh ham.",
    imagePath: "asstes/images/global_dishes/global_dishes_images/Pernil.jpg",
    foodPrice: 434.0,
    foodRate: 4.6,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "PUERTO RICO",
    dishCountryFlag: "${Assets.flageBase}PUERTORICO.svg",
    ingredientsNames: [
      "Porks",
      "Garlic",
      "Salts",
      "Peppers",
      "Oregano",
      "Vinegars",
      "Olive Oils",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}12/1-ingredient.png",
      "${Assets.gobalIngBase}12/2-ingredient.png",
      "${Assets.gobalIngBase}12/3-ingredient.png",
      "${Assets.gobalIngBase}12/4-ingredient.png",
      "${Assets.gobalIngBase}12/5-ingredient.png",
      "${Assets.gobalIngBase}12/6-ingredient.png",
      "${Assets.gobalIngBase}12/7-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Tombik Döner",
    description:
        "Tombik döner or gobit kebab is a variety of döner kebab where the shredded meat is stuffed in a bun-shaped flatbread known as pide ekmek. The bread has a crispy exterior and a soft interior.",
    imagePath:
        "asstes/images/global_dishes/global_dishes_images/Tombik-Döner.jpg",
    foodPrice: 232.0,
    foodRate: 4.6,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "TURKIYE",
    dishCountryFlag: "${Assets.flageBase}Turquie.svg",
    ingredientsNames: [
      "Ramazan pidesi",
      "Lambs",
      "Lettuces",
      "Onions",
      "Tomatoes",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}13/1-ingredient.png",
      "${Assets.gobalIngBase}13/2-ingredient.png",
      "${Assets.gobalIngBase}13/3-ingredient.png",
      "${Assets.gobalIngBase}13/4-ingredient.png",
      "${Assets.gobalIngBase}13/5-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Païdakia",
    description:
        "Grilled lamb chops are a traditional Greek dish that is popular throughout the country and usually enjoyed as the main course. Lamb chops are usually marinated in various combinations of olive oil, lemon juice, and a variety of fresh herbs before they are grilled on traditional charcoal barbecues.",
    imagePath: "asstes/images/global_dishes/global_dishes_images/Païdakia.jpg",
    foodPrice: 200.0,
    foodRate: 4.6,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "GREECE",
    dishCountryFlag: "${Assets.flageBase}Grece.svg",
    ingredientsNames: [
      "Lambs",
      "Olive Oils",
      "Thyme",
      "Oregano",
      "Rosemary",
      "Peppercorns",
      "Mustard Seeds",
      "Lemons",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}14/1-ingredient.png",
      "${Assets.gobalIngBase}14/2-ingredient.png",
      "${Assets.gobalIngBase}14/3-ingredient.png",
      "${Assets.gobalIngBase}14/4-ingredient.png",
      "${Assets.gobalIngBase}14/5-ingredient.png",
      "${Assets.gobalIngBase}14/6-ingredient.png",
      "${Assets.gobalIngBase}14/7-ingredient.png",
      "${Assets.gobalIngBase}14/8-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Provoleta",
    description:
        "In Argentina, provoleta or grilled provoleta cheese is typically enjoyed before a meal as an appetizer. It's one of the staples of the Argentine bbq asado. The semi-hard provolone is the perfect cheese for the grill, because it's compact and firm.",
    imagePath: "asstes/images/global_dishes/global_dishes_images/Provoleta.jpg",
    foodPrice: 232.0,
    foodRate: 4.6,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "ARGENTINA",
    dishCountryFlag: "${Assets.flageBase}Argentine.svg",
    ingredientsNames: [
      "Provolone Valpadana",
      "Oregano",
      "Red Chili Flakes",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}15/1-ingredient.png",
      "${Assets.gobalIngBase}15/2-ingredient.png",
      "${Assets.gobalIngBase}15/3-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Gyoza",
    description:
        "The famous Japanese gyoza are crescent-shaped dumplings that have originated from the traditional Chinese jiaozi dumplings. The recipe was slightly altered to accommodate the Japanese taste, and gyoza soon became one of the favorite Japanese meals.",
    imagePath: "asstes/images/global_dishes/global_dishes_images/Gyoza.jpg",
    foodPrice: 334.99,
    foodRate: 4.5,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "JAPAN",
    dishCountryFlag: "${Assets.flageBase}Japon.svg",
    ingredientsNames: [
      "Wheat Flours",
      "Eggs",
      "Chickens",
      "Cabbages",
      "Chives",
      "Garlic",
      "Ginger",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}16/1-ingredient.png",
      "${Assets.gobalIngBase}16/2-ingredient.png",
      "${Assets.gobalIngBase}16/3-ingredient.png",
      "${Assets.gobalIngBase}16/4-ingredient.png",
      "${Assets.gobalIngBase}16/5-ingredient.png",
      "${Assets.gobalIngBase}16/6-ingredient.png",
      "${Assets.gobalIngBase}16/7-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Guacamole",
    description:
        "Guacamole is a world-famous buttery delicacy dating back all the way to the Aztec empire of the 1500s. It's a healthy blend of ripe, mashed avocados, onions, chiles, optional tomatillos and selected seasonings such as sea salt and coriander.",
    imagePath: "asstes/images/global_dishes/global_dishes_images/Guacamole.jpg",
    foodPrice: 232.0,
    foodRate: 4.5,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "MEXICO",
    dishCountryFlag: "${Assets.flageBase}Mexique.svg",
    ingredientsNames: [
      "Avocados",
      "Limes",
      "Onions",
      "Chili pepper",
      "Coriander",
      "Salts",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}17/1-ingredient.png",
      "${Assets.gobalIngBase}17/2-ingredient.png",
      "${Assets.gobalIngBase}17/3-ingredient.png",
      "${Assets.gobalIngBase}17/4-ingredient.png",
      "${Assets.gobalIngBase}17/5-ingredient.png",
      "${Assets.gobalIngBase}17/6-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Dondurma",
    description:
        "Turkish ice cream is believed to originate from the city of Maraş—hence the name—and what really sets it apart from other varieties is its resistance to melting and a particularly dense, chewy texture. These qualities are brought by adding two thickening agents to the basic milk and sugar mixture: Arab gum, also known as mastic resin, and salep—a type of flour made from the root of the early purple orchid.",
    imagePath: "asstes/images/global_dishes/global_dishes_images/Dondurma.jpg",
    foodPrice: 223.0,
    foodRate: 4.5,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "Turkiye",
    dishCountryFlag: "${Assets.flageBase}Turquie.svg",
    ingredientsNames: [
      "Masticha ",
      "Salep Flours",
      "Milks",
      "Sugars",
      "Cinnamon",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}18/1-ingredient.png",
      "${Assets.gobalIngBase}18/2-ingredient.png",
      "${Assets.gobalIngBase}18/3-ingredient.png",
      "${Assets.gobalIngBase}18/4-ingredient.png",
      "${Assets.gobalIngBase}18/5-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Poke",
    description:
        "Poke is a traditional Hawaiian dish that is made with small pieces of fresh and raw fish or seafood, which are combined with finely chopped vegetables, herbs, condiments, and seasonings. Although traditional poke uses either ahi tuna (yellowfin tuna) or octopus, the variations on this dish are endless these days, including poke with salmon, mussels, crabmeat, or oysters, as well as vegetarian versions with diced avocados.",
    imagePath: "asstes/images/global_dishes/global_dishes_images/Poke.jpg",
    foodPrice: 16.0,
    foodRate: 4.5,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "America",
    dishCountryFlag: "${Assets.flageBase}america.svg",
    ingredientsNames: [
      "TUNA",
      "ONION",
      "SCALLIONS",
      "SESAME SEEDS",
      "HOT PEPPERS",
      "SOY SAUCE",
      "SESAME OIL",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}19/1-ingredient.png",
      "${Assets.gobalIngBase}19/2-ingredient.png",
      "${Assets.gobalIngBase}19/3-ingredient.png",
      "${Assets.gobalIngBase}19/4-ingredient.png",
      "${Assets.gobalIngBase}19/5-ingredient.png",
      "${Assets.gobalIngBase}19/6-ingredient.png",
      "${Assets.gobalIngBase}19/7-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Manti",
    description:
        "Manti are traditional Turkish dumplings filled with spiced ground meat and onions. The dumplings are most commonly topped with a sauce consisting of yogurt and garlic. The name of the dish is derived from mantu, meaning dumplings, and they were originally brought over from Central Asia to Türkiye by nomadic Turkish tribes in the 13th century.",
    imagePath: "asstes/images/global_dishes/global_dishes_images/Manti.jpg",
    foodPrice: 25.0,
    foodRate: 4.5,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "TURKIYE",
    dishCountryFlag: "${Assets.flageBase}Turquie.svg",
    ingredientsNames: [
      "WHEAT FLOUR",
      "BEEF",
      "EGGS",
      "OLIVE OIL",
      "ONION",
      "BLACK PEPPER",
      "YOGURT",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}20/1-ingredient.png",
      "${Assets.gobalIngBase}20/2-ingredient.png",
      "${Assets.gobalIngBase}20/3-ingredient.png",
      "${Assets.gobalIngBase}20/4-ingredient.png",
      "${Assets.gobalIngBase}20/5-ingredient.png",
      "${Assets.gobalIngBase}20/6-ingredient.png",
      "${Assets.gobalIngBase}20/7-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Raclette",
    description:
        "Raclette is a national dish that shares its name with a slightly nutty Swiss cheese made from cow's milk, an appliance for preparing the dish, and a full dining experience. Extremely popular in the ski region Valais and other parts of the Swiss Alps, where it also originated, raclette was invented by the Swiss mountain shepherds who used to gather around a fire while roasting potatoes.",
    imagePath: "asstes/images/global_dishes/global_dishes_images/Raclette.jpg",
    foodPrice: 23.0,
    foodRate: 4.5,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "Switzerland",
    dishCountryFlag: "${Assets.flageBase}Suisse.svg",
    ingredientsNames: [
      "Raclette de Savoie",
      "Potatoes",
      "Pickled Cucumbers",
      "Onions",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}21/1-ingredient.png",
      "${Assets.gobalIngBase}21/2-ingredient.png",
      "${Assets.gobalIngBase}21/3-ingredient.png",
      "${Assets.gobalIngBase}21/4-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Tikka",
    description:
        "Indian tikka is a dish consisting of boneless meat, usually chicken, that is cut into smaller pieces and marinated in yogurt and traditional Indian spices such as turmeric, cumin, coriander, cayenne pepper, chili, garlic, and ginger. The meat is roasted over charcoal in a tandoor, the traditional cylindrical clay oven.",
    imagePath: "asstes/images/global_dishes/global_dishes_images/Tikka.jpg",
    foodPrice: 234.0,
    foodRate: 4.5,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "India",
    dishCountryFlag: "${Assets.flageBase}Inde.svg",
    ingredientsNames: [
      "CHICKEN",
      "PANEER",
      "DAHI",
      "Garam",
      "CUMIN",
      "CORIANDER",
      "KASHMIRI CHILI",
      "MUSTARD OIL",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}22/1-ingredient.png",
      "${Assets.gobalIngBase}22/2-ingredient.png",
      "${Assets.gobalIngBase}22/3-ingredient.png",
      "${Assets.gobalIngBase}22/4-ingredient.png",
      "${Assets.gobalIngBase}22/5-ingredient.png",
      "${Assets.gobalIngBase}22/6-ingredient.png",
      "${Assets.gobalIngBase}22/7-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Kaiserschmarrn",
    description:
        "Also known as the Emperor's mess, this Austrian dessert can be described as a fluffy, lightly caramelized, scrambled pancake. Legend has it that kaiserschmarrn was the favorite dessert of Kaiser Franz Joseph I, after whom it was named.",
    imagePath:
        "asstes/images/global_dishes/global_dishes_images/Kaiserschmarrn.jpg",
    foodPrice: 232.0,
    foodRate: 4.5,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "AUSTRIA",
    dishCountryFlag: "${Assets.flageBase}Australie.svg",
    ingredientsNames: [
      "EGGS",
      "MILK",
      "WHEAT FLOUR",
      "SUGAR",
      "RAISINS",
      "RUM",
      "LEMON",
      "VANILLA",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}23/1-ingredient.png",
      "${Assets.gobalIngBase}23/2-ingredient.png",
      "${Assets.gobalIngBase}23/3-ingredient.png",
      "${Assets.gobalIngBase}23/4-ingredient.png",
      "${Assets.gobalIngBase}23/5-ingredient.png",
      "${Assets.gobalIngBase}23/6-ingredient.png",
      "${Assets.gobalIngBase}23/7-ingredient.png",
      "${Assets.gobalIngBase}23/8-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Medovik",
    description:
        "Medovik is a popular Russian layered honey cake consisting of honey-infused, almost biscuit-like sponges that are coated with thin layers of cream. Although there are numerous variations of the cake, the custard is usually prepared with whipped cream or various combinations of condensed milk and butter.",
    imagePath: "asstes/images/global_dishes/global_dishes_images/Medovik.jpg",
    foodPrice: 97.0,
    foodRate: 4.3,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "RUSSIA",
    dishCountryFlag: "${Assets.flageBase}Russie.svg",
    ingredientsNames: [
      "FLOUR",
      "EGGS",
      "SUGAR",
      "HONEY",
      "Baking Powder",
      "SOUR CREAM",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}24/1-ingredient.png",
      "${Assets.gobalIngBase}24/2-ingredient.png",
      "${Assets.gobalIngBase}24/3-ingredient.png",
      "${Assets.gobalIngBase}24/4-ingredient.png",
      "${Assets.gobalIngBase}24/5-ingredient.png",
      "${Assets.gobalIngBase}24/6-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Jianbing",
    description:
        "A favorite breakfast item in China sold by numerous street food vendors early in the morning, jianbing or fried pancake is a thin and savory crêpe-like pancake that is made by spreading batter over a hot, cast-iron slab with a wooden paddle.",
    imagePath: "asstes/images/global_dishes/global_dishes_images/Jianbing.jpg",
    foodPrice: 76.0,
    foodRate: 4.5,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "AUSTRIA",
    dishCountryFlag: "${Assets.flageBase}Australie.svg",
    ingredientsNames: [
      "Wheat Flours",
      "EGGS",
      "SCALLIONS",
      "Sweet bean sauce",
      "Sesame Seeds",
      "Vegetable Oils",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}25/1-ingredient.png",
      "${Assets.gobalIngBase}25/2-ingredient.png",
      "${Assets.gobalIngBase}25/3-ingredient.png",
      "${Assets.gobalIngBase}25/4-ingredient.png",
      "${Assets.gobalIngBase}25/5-ingredient.png",
      "${Assets.gobalIngBase}25/6-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Escondidinho",
    description:
        "Escondidinho is a traditional Brazilian casserole. It can be made with a variety of ingredients beef, chicken, fish, pork, or shrimp. The original one is called escondidinho de carne seca, made with a combination of dried and salted meat and mashed potatoes.",
    imagePath:
        "asstes/images/global_dishes/global_dishes_images/Escondidinho.jpg",
    foodPrice: 34.0,
    foodRate: 4.5,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "BRAZIL",
    dishCountryFlag: "${Assets.flageBase}Belize.svg",
    ingredientsNames: [
      "CARNE SECA",
      "CARNE DE SOL",
      "CASSAVA",
      "Queijo de Coalho",
      "Manteiga de garrafa",
      "ONION",
      "HOT PEPPERS",
      "MILK",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}26/1-ingredient.png",
      "${Assets.gobalIngBase}26/2-ingredient.png",
      "${Assets.gobalIngBase}26/3-ingredient.png",
      "${Assets.gobalIngBase}26/4-ingredient.png",
      "${Assets.gobalIngBase}26/5-ingredient.png",
      "${Assets.gobalIngBase}26/6-ingredient.png",
      "${Assets.gobalIngBase}26/7-ingredient.png",
      "${Assets.gobalIngBase}26/8-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Boiled Maine Lobster",
    description:
        "Boiling is the most popular and simplest way of preparing a Maine lobster. Live lobsters are plopped into a large pot of boiling water seasoned with sea salt and cooked depending on the size of the lobster — the bigger the lobster, the longer the cooking time.",
    imagePath:
        "asstes/images/global_dishes/global_dishes_images/Boiled-Maine-Lobster.jpg",
    foodPrice: 80.0,
    foodRate: 4.6,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "United States of America",
    dishCountryFlag: "${Assets.flageBase}america.svg",
    ingredientsNames: [
      "American lobster",
      "SALT",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}27/1-ingredient.png",
      "${Assets.gobalIngBase}27/2-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Mutabal",
    description:
        "Mutabal is a Middle Eastern dip that's usually made with a combination of roasted eggplants, tahini, lemon juice, garlic, yogurt, olive oil, and salt. The ingredients are blended or mashed together until the dip develops a desired consistency, either smooth or a bit more coarse.",
    imagePath: "asstes/images/global_dishes/global_dishes_images/Mutabal.jpg",
    foodPrice: 34.0,
    foodRate: 4.5,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "LEBANON",
    dishCountryFlag: "${Assets.flageBase}Liban.svg",
    ingredientsNames: [
      "EGGPLANT",
      "TAHINI",
      "LEMON JUICE",
      "GARLIC",
      "YOGURT",
      "PARSLEY",
      "POMEGRANATE",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}28/1-ingredient.png",
      "${Assets.gobalIngBase}28/2-ingredient.png",
      "${Assets.gobalIngBase}28/3-ingredient.png",
      "${Assets.gobalIngBase}28/4-ingredient.png",
      "${Assets.gobalIngBase}28/5-ingredient.png",
      "${Assets.gobalIngBase}28/6-ingredient.png",
      "${Assets.gobalIngBase}28/7-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Koldūnai",
    description:
        "Known as koldūnai in Lithuania, kalduny in Belarus and kołduny in Poland,  these stuffed dumplings boiled in salted water are a staple of regional cuisine. Traditionally filled with minced pork, beef, chicken, curd cheese, or mushrooms, they make for an excellent lunch choice and can be enjoyed with a variety of garnishes, from butter and black pepper to mayonnaise, sour cream, crispy bacon, or spirgučiais (a type of pork rind).",
    imagePath: "asstes/images/global_dishes/global_dishes_images/Koldūnai.jpg",
    foodPrice: 242.0,
    foodRate: 4.2,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "LITHUANIA",
    dishCountryFlag: "${Assets.flageBase}Liban.svg",
    ingredientsNames: [
      "WHEAT FLOUR",
      "EGGS",
      "CHICKEN",
      "MUSHROOMS",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}29/1-ingredient.png",
      "${Assets.gobalIngBase}29/2-ingredient.png",
      "${Assets.gobalIngBase}29/3-ingredient.png",
      "${Assets.gobalIngBase}29/4-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Giouvetsi",
    description:
        "This classic Greek casserole consists of a combination of pasta and tomato-braised meat that is prepared as a one-pot oven dish. Although veal is the traditional choice, various types of meat may be employed, while the rich tomato sauce is usually seasoned with cinnamon, allspice, red wine, cloves, and bay leaves.",
    imagePath: "asstes/images/global_dishes/global_dishes_images/Giouvetsi.jpg",
    foodPrice: 53.0,
    foodRate: 4.5,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "GREECE",
    dishCountryFlag: "${Assets.flageBase}Grece.svg",
    ingredientsNames: [
      "ORZO",
      "VEAL",
      "ONION",
      "CARROT",
      "TOMATO",
      "CINNAMON",
      "RED WINE",
      "OLIVE OIL",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}30/1-ingredient.png",
      "${Assets.gobalIngBase}30/2-ingredient.png",
      "${Assets.gobalIngBase}30/3-ingredient.png",
      "${Assets.gobalIngBase}30/4-ingredient.png",
      "${Assets.gobalIngBase}30/5-ingredient.png",
      "${Assets.gobalIngBase}30/6-ingredient.png",
      "${Assets.gobalIngBase}30/7-ingredient.png",
      "${Assets.gobalIngBase}30/8-ingredient.png",
    ],
  ),
];

List<FoodModel> pageViewGlobalDishes = <FoodModel>[
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Pizza Napoletana",
    description:
        "Italy's most emblematic culinary creation, the genuine pizza Napoletana is made with just a few simple ingredients and prepared in only two variations – marinara, the basic Neapolitan pizza topped with a tomato-based sauce flavored with garlic and oregano, and margherita, which is topped with tomatoes, mozzarella, and fresh basil leaves, a delicious combination whose colors are said to represent the Italian flag.",
    imagePath:
        "asstes/images/global_dishes/global_dishes_images/Pizza-Napoletana.jpg",
    foodPrice: 24.0,
    foodRate: 4.8,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "NAPLES,ITALY",
    dishCountryFlag: "${Assets.flageBase}Italie.svg",
    ingredientsNames: [
      "00 Flour",
      "Tomatoes",
      "Mozzarella",
      "Basil",
      "Olive Oils",
      "Oregano",
      "Yeasts",
      "Salts",
    ],
    ingredientsImages: <String>[
      "${Assets.gobalIngBase}1/1-ingredient.png",
      "${Assets.gobalIngBase}1/2-ingredient.png",
      "${Assets.gobalIngBase}1/3-ingredient.png",
      "${Assets.gobalIngBase}1/4-ingredient.png",
      "${Assets.gobalIngBase}1/5-ingredient.png",
      "${Assets.gobalIngBase}1/6-ingredient.png",
      "${Assets.gobalIngBase}1/7-ingredient.png",
      "${Assets.gobalIngBase}1/8-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Picanha",
    description:
        "Picanha is a fresh cut of beef that's especially popular and highly prized in Brazil. In the US, it's called sirloin cap, and in the UK, it's known as the rump cap. Picanha is situated on the back side of the animal, above the butt, where it sits on a fat cap.",
    imagePath: "asstes/images/global_dishes/global_dishes_images/Picanha.jpg",
    foodPrice: 90.0,
    foodRate: 4.7,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "BRAZIL",
    dishCountryFlag: "${Assets.flageBase}Belize.svg",
    ingredientsNames: [
      "Beef Cattle Breeds",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}2/1-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Guotie",
    description:
        "The pan-fried variety of the Chinese jiaozi dumpling, known as guotie, is a Northern Chinese dumpling typically filled with minced pork, Chinese cabbage, scallions, ginger, rice wine, and sesame seed oil. Crunchy and soft textures are achieved by a special method of preparing; while the bottom of the dumpling is frying, a small amount of liquid is added to the pan which is then covered, thus allowing the rest of the dumpling and the filling to steam.",
    imagePath: "asstes/images/global_dishes/global_dishes_images/Guotie.jpg",
    foodPrice: 81.0,
    foodRate: 4.7,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "CHINA",
    dishCountryFlag: "${Assets.flageBase}Chine.svg",
    ingredientsNames: [
      "Wheat Flours",
      "Shrimps",
      "Scallions",
      "Shallots",
      "Ginger",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}3/1-ingredient.png",
      "${Assets.gobalIngBase}3/2-ingredient.png",
      "${Assets.gobalIngBase}3/3-ingredient.png",
      "${Assets.gobalIngBase}3/4-ingredient.png",
      "${Assets.gobalIngBase}3/5-ingredient.png",
      "${Assets.gobalIngBase}3/6-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "GlobalDishe",
    foodName: "Roti canai",
    description:
        "Roti canai is a traditional pan-fried flatbread made with flour, water, eggs, and fat of Indian origin, but mainly associated with Malaysia, and surrounding countries like Indonesia, Brunei, and Thailand. The dough for roti canai is repeatedly folded, so the final product has a layered texture, a soft interior, and a crispy outer layer.",
    imagePath:
        "asstes/images/global_dishes/global_dishes_images/Roti-canai.jpg",
    foodPrice: 90.0,
    foodRate: 4.7,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    dishCountry: "MALAYSIA",
    dishCountryFlag: "${Assets.flageBase}Malaisie.svg",
    ingredientsNames: [
      "Wheat Flours",
      "Ghee",
      "Vegetable Oils",
      "Salts",
    ],
    ingredientsImages: [
      "${Assets.gobalIngBase}4/1-ingredient.png",
      "${Assets.gobalIngBase}4/2-ingredient.png",
      "${Assets.gobalIngBase}4/3-ingredient.png",
      "${Assets.gobalIngBase}4/4-ingredient.png",
    ],
  ),
];
