import 'package:foodapp/constants/assets.dart';
import 'package:foodapp/data_layer/data_base/global_demo_data_model.dart';
import 'package:foodapp/data_layer/data_models/random_data.dart';

List<FoodModel> saladDamoData = [
  FoodModel(
    foodType: "Salad",
    foodName: "Coleslaw",
    description:
        "Originating from the Dutch term koolsla, meaning cabbage salad, coleslaw is nowadays a true American staple and a side dish that's often served with barbecued meat or fried chicken. Originally, it was brought over to New York state in the 18th century by the Dutch settlers.",
    imagePath: "${Assets.saladBase}Coleslaw.jpg",
    foodPrice: 23.0,
    foodRate: 3.5,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    ingredientsImages: [
      "${Assets.saladIngBase}1/1-ingredient.png",
      "${Assets.saladIngBase}1/2-ingredient.png",
      "${Assets.saladIngBase}1/3-ingredient.png",
      "${Assets.saladIngBase}1/4-ingredient.png",
      "${Assets.saladIngBase}1/5-ingredient.png",
      "${Assets.saladIngBase}1/6-ingredient.png",
    ],
    ingredientsNames: [
      "CABBAGE",
      "CARROT",
      "MAYONNAISE",
      "SOUR CREAM",
      "VINEGAR",
      "SUGAR",
    ],
  ),
  FoodModel(
    foodType: "Salad",
    foodName: "Caesar salad",
    description:
        "The iconic Caesar salad was named after its creator Cesare (Caesar) Cardini, an Italian immigrant who lived in San Diego but, circumventing Prohibition laws in the United States, operated a popular restaurant in Tijuana, just south of the Mexican border.",
    imagePath: "${Assets.saladBase}Caesar-salad.jpg",
    foodPrice: 34.0,
    foodRate: 3.9,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    ingredientsImages: [
      "${Assets.saladIngBase}2/1-ingredient.png",
      "${Assets.saladIngBase}2/2-ingredient.png",
      "${Assets.saladIngBase}2/3-ingredient.png",
      "${Assets.saladIngBase}2/4-ingredient.png",
      "${Assets.saladIngBase}2/5-ingredient.png",
      "${Assets.saladIngBase}2/6-ingredient.png",
      "${Assets.saladIngBase}2/7-ingredient.png",
      "${Assets.saladIngBase}2/8-ingredient.png",
    ],
    ingredientsNames: [
      "LETTUCE",
      "CROUTONS",
      "Parmigiano",
      "EGGS",
      "GARLIC",
      "LEMON",
      "Worcestershire",
      "OLIVE OIL",
    ],
  ),
  FoodModel(
    foodType: "Salad",
    foodName: "Horiatiki salata",
    description:
        "Greek salad, also known as village salad or horiatiki is the national dish of Greece, consisting of quartered tomatoes, sliced red onions, and chunky slices of cucumber. Depending on the region, there can also be olives, green peppers, feta cheese, oregano, salt, pepper, or a typical dressing made from olive oil and lemon or vinegar (optionally). When feta cheese is present in the salad, it is usually just sliced, but in some cases it's mixed in with a fork until slightly crumbled.",
    imagePath: "${Assets.saladBase}Horiatiki-salata.jpg",
    foodPrice: 21.0,
    foodRate: 4.4,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    ingredientsImages: [
      "${Assets.saladIngBase}3/1-ingredient.png",
      "${Assets.saladIngBase}3/2-ingredient.png",
      "${Assets.saladIngBase}3/3-ingredient.png",
      "${Assets.saladIngBase}3/4-ingredient.png",
      "${Assets.saladIngBase}3/5-ingredient.png",
      "${Assets.saladIngBase}3/6-ingredient.png",
      "${Assets.saladIngBase}3/7-ingredient.png",
      "${Assets.saladIngBase}3/8-ingredient.png",
    ],
    ingredientsNames: [
      "FETA",
      "Eliá ",
      "RED ONION",
      "CUCUMBER",
      "BELL PEPPER",
      "TOMATO",
      "OREGANO",
      "OLIVE OIL",
    ],
  ),
  FoodModel(
    foodType: "Salad",
    foodName: "Caprese Salad",
    description:
        "Nothing embodies the essence of summer in southern Italy like vibrant colors of the flavorful insalata Caprese, a true classic of Neapolitan cuisine. The perfect combination of ripe, sun-kissed tomatoes, creamy mozzarella and fresh basil - this simple salad is believed to have originated on the island of Capri, hence the name.",
    imagePath: "${Assets.saladBase}Caprese-Salad.jpg",
    foodPrice: 22.99,
    foodRate: 4.3,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    ingredientsImages: [
      "${Assets.saladIngBase}4/1-ingredient.png",
      "${Assets.saladIngBase}4/2-ingredient.png",
      "${Assets.saladIngBase}4/3-ingredient.png",
      "${Assets.saladIngBase}4/4-ingredient.png",
    ],
    ingredientsNames: [
      "TOMATO",
      "MOZZARELLA",
      "BASIL",
      "OLIVE OIL",
    ],
  ),
  FoodModel(
    foodType: "Salad",
    foodName: "Macaroni Salad",
    description:
        "Usually an obligatory element of the Hawaiian plate lunch, macaroni salad is a slightly tangy, sweet, cold salad consisting of overcooked elbow macaroni pasta dressed with milk-thinned mayonnaise. The pasta must be overcooked as it helps absorb the dressing.",
    imagePath: "${Assets.saladBase}Macaroni-Salad.jpg",
    foodPrice: 32.0,
    foodRate: 3.1,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    ingredientsImages: [
      "${Assets.saladIngBase}5/1-ingredient.png",
      "${Assets.saladIngBase}5/2-ingredient.png",
      "${Assets.saladIngBase}5/3-ingredient.png",
      "${Assets.saladIngBase}5/4-ingredient.png",
      "${Assets.saladIngBase}5/5-ingredient.png",
      "${Assets.saladIngBase}5/6-ingredient.png",
      "${Assets.saladIngBase}5/7-ingredient.png",
      "${Assets.saladIngBase}5/8-ingredient.png",
    ],
    ingredientsNames: [
      "MACARONI",
      "CARROT",
      "ONION",
      "MAYONNAISE",
      "MILK",
      "SUGAR",
      "BLACK PEPPER",
      "SALT",
    ],
  ),
  FoodModel(
    foodType: "Salad",
    foodName: "Fattoush",
    description:
        "Fattoush is a simple salad made with traditional pita bread as a base on which the rest of the ingredients are built on. Pita bread is torn or cut into small bite-sized pieces, then toasted, grilled, or fried. It is then mixed with a variety of vegetables such as lettuce, radish, crunchy cucumbers, cherry tomatoes or regular tomatoes, peppers, onions, and (occasionally) garlic.",
    imagePath: "${Assets.saladBase}Fattoush.jpg",
    foodPrice: 21.0,
    foodRate: 4.4,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    ingredientsImages: [
      "${Assets.saladIngBase}6/1-ingredient.png",
      "${Assets.saladIngBase}6/2-ingredient.png",
      "${Assets.saladIngBase}6/3-ingredient.png",
      "${Assets.saladIngBase}6/4-ingredient.png",
      "${Assets.saladIngBase}6/5-ingredient.png",
      "${Assets.saladIngBase}6/6-ingredient.png",
      "${Assets.saladIngBase}6/7-ingredient.png",
      "${Assets.saladIngBase}6/8-ingredient.png",
    ],
    ingredientsNames: [
      "PITA BREAD",
      "LETTUCE",
      "PEPPERS",
      "CHERRY ",
      "MINT",
      "OLIVE OIL",
      "SUMAC",
      "POMEGRANATE ",
    ],
  ),
  FoodModel(
    foodType: "Salad",
    foodName: "Olivier Salad",
    description:
        "Olivier salad is a Russian salad with variable ingredients, but it is typically made with chopped vegetables, meat, and mayonnaise. The key ingredients include diced potatoes, vegetables, eggs, chicken, or ham. This salad is one of the most important appetizers at the New Year's salad buffets in Russia, as well as in some of the other countries of the former USSR.",
    imagePath: "${Assets.saladBase}Olivier-Salad.jpg",
    foodPrice: 43.0,
    foodRate: 4.0,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    ingredientsImages: [
      "${Assets.saladIngBase}7/1-ingredient.png",
      "${Assets.saladIngBase}7/2-ingredient.png",
      "${Assets.saladIngBase}7/3-ingredient.png",
      "${Assets.saladIngBase}7/4-ingredient.png",
      "${Assets.saladIngBase}7/5-ingredient.png",
      "${Assets.saladIngBase}7/6-ingredient.png",
      "${Assets.saladIngBase}7/7-ingredient.png",
    ],
    ingredientsNames: [
      "POTATOES",
      "MAYONNAISE",
      "PEAS",
      "EGGS",
      "DILL",
      "PICKLING",
      "SCALLIONS",
    ],
  ),
  FoodModel(
    foodType: "Salad",
    foodName: "Kisir",
    description:
        "Kisir is a classic Turkish salad made with thin bulgur wheat, tomatoes, mint, garlic, parsley, and either lemon juice or sour pomegranate molasses. Red pepper flakes are often added to the salad to make it spicier. Lemon juice is typically used in northwestern Türkiye, while pomegranate molasses is more commonly used in the southeast of the country.",
    imagePath: "${Assets.saladBase}Kisir.jpg",
    foodPrice: 44.0,
    foodRate: 4.1,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    ingredientsImages: [
      "${Assets.saladIngBase}8/1-ingredient.png",
      "${Assets.saladIngBase}8/2-ingredient.png",
      "${Assets.saladIngBase}8/3-ingredient.png",
      "${Assets.saladIngBase}8/4-ingredient.png",
      "${Assets.saladIngBase}8/5-ingredient.png",
      "${Assets.saladIngBase}8/6-ingredient.png",
      "${Assets.saladIngBase}8/7-ingredient.png",
      "${Assets.saladIngBase}8/8-ingredient.png",
    ],
    ingredientsNames: [
      "BULGUR",
      "TOMATO",
      "LEMON",
      "Pomegranate ",
      "MINT",
      "PARSLEY",
      "HOT PEPPERS",
      "GARLIC",
    ],
  ),
  FoodModel(
    foodType: "Salad",
    foodName: "Tabbouleh",
    description:
        "Tabbouleh is a colorful Lebanese national dish that is usually considered a salad, with a crunchy and chewy texture, made with fresh, finely chopped parsley leaves, olive oil, bulgur wheat, and chopped mint leaves as a base. It originated in the mountains of Lebanon and Syria, where edible herbs that are used in tabbouleh were consumed by Arabs since Medieval times.",
    imagePath: "${Assets.saladBase}Tabbouleh.jpg",
    foodPrice: 23.0,
    foodRate: 4.1,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    ingredientsImages: [
      "${Assets.saladIngBase}9/1-ingredient.png",
      "${Assets.saladIngBase}9/2-ingredient.png",
      "${Assets.saladIngBase}9/3-ingredient.png",
      "${Assets.saladIngBase}9/4-ingredient.png",
      "${Assets.saladIngBase}9/5-ingredient.png",
      "${Assets.saladIngBase}9/6-ingredient.png",
      "${Assets.saladIngBase}9/7-ingredient.png",
    ],
    ingredientsNames: [
      "BULGUR",
      "MINT",
      "PARSLEY",
      "TOMATO",
      "OLIVE OIL",
      "ONION",
      "LEMON",
    ],
  ),
  FoodModel(
    foodType: "Salad",
    foodName: "Vinegret",
    description:
        "Originally invented in the 19th century, vinegret is the oldest, extremely popular Russian salad usually consisting of boiled beets, potatoes, and carrots combined with diced pickles, sauerkraut, and onions. The name of the salad is derived from the French term vinaigrette, which denotes an oily salad dressing in France.",
    imagePath: "${Assets.saladBase}Vinegret.jpg",
    foodPrice: 112.0,
    foodRate: 3.8,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    ingredientsImages: [
      "${Assets.saladIngBase}10/1-ingredient.png",
      "${Assets.saladIngBase}10/2-ingredient.png",
      "${Assets.saladIngBase}10/3-ingredient.png",
      "${Assets.saladIngBase}10/4-ingredient.png",
      "${Assets.saladIngBase}10/5-ingredient.png",
      "${Assets.saladIngBase}10/6-ingredient.png",
      "${Assets.saladIngBase}10/7-ingredient.png",
      "${Assets.saladIngBase}10/8-ingredient.png",
    ],
    ingredientsNames: [
      "VINEGAR",
      "Sunflower Oils",
      "MUSTARD",
      "SAUERKRAUT",
      "ONION",
      "CARROT",
      "POTATOES",
      "BEET",
    ],
  ),
  FoodModel(
    foodType: "Salad",
    foodName: "Horta",
    description:
        "Horta is a traditional Greek salad consisting of steamed or boiled greens and weeds that are drizzled with lemon juice and olive oil. The greens usually include dandelion, vleeta, nettles, wild spinach, mustard greens, and chicory. The flavor of the salad can be more or less bitter, depending on the plant.",
    imagePath: "${Assets.saladBase}Horta.jpg",
    foodPrice: 57.0,
    foodRate: 4.5,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    ingredientsImages: [
      "${Assets.saladIngBase}11/1-ingredient.png",
      "${Assets.saladIngBase}11/2-ingredient.png",
      "${Assets.saladIngBase}11/3-ingredient.png",
      "${Assets.saladIngBase}11/4-ingredient.png",
      "${Assets.saladIngBase}11/5-ingredient.png",
      "${Assets.saladIngBase}11/6-ingredient.png",
    ],
    ingredientsNames: [
      "DANDELIONS",
      "NETTLE",
      "SPINACH",
      "CHICORY",
      "LEMON",
      "OLIVE OIL",
    ],
  ),
  FoodModel(
    foodType: "Salad",
    foodName: "Chinese Chicken Salad",
    description: "description",
    imagePath: "${Assets.saladBase}Chinese-Chicken-Salad.jpg",
    foodPrice: 43.0,
    foodRate: 4.4,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    ingredientsImages: [
      "${Assets.saladIngBase}12/1-ingredient.png",
      "${Assets.saladIngBase}12/2-ingredient.png",
      "${Assets.saladIngBase}12/3-ingredient.png",
      "${Assets.saladIngBase}12/4-ingredient.png",
      "${Assets.saladIngBase}12/5-ingredient.png",
      "${Assets.saladIngBase}12/6-ingredient.png",
      "${Assets.saladIngBase}12/7-ingredient.png",
      "${Assets.saladIngBase}12/8-ingredient.png",
    ],
    ingredientsNames: [
      "CHICKEN",
      "NAPA CABBAGE",
      "LETTUCE",
      "CARROT",
      "RADICCHIO",
      "WATERCRESS",
      "NOODLES",
      "SESAME SEEDS",
    ],
  ),
  FoodModel(
    foodType: "Salad",
    foodName: "Mizeria",
    description:
        "Refreshing and easy to make, mizeria is one of the most famous Polish salads. It consists of thinly sliced cucumbers that are seasoned with salt and pepper, then mixed with creamy sour cream or yogurt. The essential part of mizeria is a handful of freshly chopped dill, one of the favorite herbs used in Polish cuisine.",
    imagePath: "${Assets.saladBase}Mizeria.jpg",
    foodPrice: 23.0,
    foodRate: 4.1,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    ingredientsImages: [
      "${Assets.saladIngBase}13/1-ingredient.png",
      "${Assets.saladIngBase}13/2-ingredient.png",
      "${Assets.saladIngBase}13/3-ingredient.png",
    ],
    ingredientsNames: [
      "CUCUMBER",
      "SOUR CREAM",
      "DILL",
    ],
  ),
  FoodModel(
    foodType: "Salad",
    foodName: "Kartoffelsalat",
    description:
        "Kartoffelsalat is a traditional German potato salad hailing from the region of Swabia in Southern Germany. It typically consists of boiled and sliced potatoes, chopped onions, beef broth, white vinegar, oil, mild German mustard, sugar, and pepper.",
    imagePath: "${Assets.saladBase}Kartoffelsalat.jpg",
    foodPrice: 34.0,
    foodRate: 4.0,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    ingredientsImages: [
      "${Assets.saladIngBase}14/1-ingredient.png",
      "${Assets.saladIngBase}14/2-ingredient.png",
      "${Assets.saladIngBase}14/3-ingredient.png",
      "${Assets.saladIngBase}14/4-ingredient.png",
      "${Assets.saladIngBase}14/5-ingredient.png",
      "${Assets.saladIngBase}14/6-ingredient.png",
    ],
    ingredientsNames: [
      "POTATOES",
      "ONION",
      "VINEGAR",
      "MUSTARD",
      "CHIVES",
      "BLACK PEPPER",
    ],
  ),
  FoodModel(
    foodType: "Salad",
    foodName: "Yusheng",
    description:
        "Usually consumed during the Chinese New Year celebrations, yusheng is a tasty salad made with slices of raw fish and shredded vegetables which are seasoned with spices and various toppings such as peanuts and sesame seeds. The dish is additionally flavored with yusheng sauce, most commonly consisting of plum sauce and sesame oil.",
    imagePath: "${Assets.saladBase}Yusheng.jpg",
    foodPrice: 39.0,
    foodRate: 3.1,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    ingredientsImages: [
      "${Assets.saladIngBase}15/1-ingredient.png",
      "${Assets.saladIngBase}15/2-ingredient.png",
      "${Assets.saladIngBase}15/3-ingredient.png",
      "${Assets.saladIngBase}15/4-ingredient.png",
      "${Assets.saladIngBase}15/5-ingredient.png",
      "${Assets.saladIngBase}15/6-ingredient.png",
      "${Assets.saladIngBase}15/7-ingredient.png",
      "${Assets.saladIngBase}15/8-ingredient.png",
    ],
    ingredientsNames: [
      "SALMON",
      "TARO",
      "CARROT",
      "CUCUMBER",
      "GINGER",
      "MANGO",
      "SCALLIONS",
      "PEANUTS",
    ],
  ),
  FoodModel(
    foodType: "Salad",
    foodName: "Piyaz",
    description:
        "Piyaz is a traditional Turkish salad. In most of the country, it's a general term for a dish of dried beans, parsley, onions, and sumac. In Antalya, however, piyaz also contains a rich and smooth sauce consisting of tahini, lemon juice, and vinegar.",
    imagePath: "${Assets.saladBase}Piyaz.jpg",
    foodPrice: 232.0,
    foodRate: 4.2,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    ingredientsImages: [
      "${Assets.saladIngBase}16/1-ingredient.png",
      "${Assets.saladIngBase}16/2-ingredient.png",
      "${Assets.saladIngBase}16/3-ingredient.png",
      "${Assets.saladIngBase}16/4-ingredient.png",
      "${Assets.saladIngBase}16/5-ingredient.png",
      "${Assets.saladIngBase}16/6-ingredient.png",
      "${Assets.saladIngBase}16/7-ingredient.png",
      "${Assets.saladIngBase}16/8-ingredient.png",
    ],
    ingredientsNames: [
      "BEANS",
      "PARSLEY",
      "TOMATO",
      "ONION",
      "SUMAC",
      "GARLIC",
      "SESAME SEEDS",
      "LEMON JUICE",
    ],
  ),
  FoodModel(
    foodType: "Salad",
    foodName: "Patatosalata",
    description:
        "Greek potato salad is incredibly versatile and can complement various Greek dishes. It usually consists of large bite-sized potato chunks that are coated in a flavorful dressing based on olive oil, mustard, yogurt, or mayonnaise. The salad is easily adapted with various additions that may include different vegetables, boiled eggs, olives, and fresh herbs such as dill or parsley.",
    imagePath: "${Assets.saladBase}Patatosalata.jpg",
    foodPrice: 11.0,
    foodRate: 4.1,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    ingredientsImages: [
      "${Assets.saladIngBase}17/1-ingredient.png",
      "${Assets.saladIngBase}17/2-ingredient.png",
      "${Assets.saladIngBase}17/3-ingredient.png",
      "${Assets.saladIngBase}17/4-ingredient.png",
      "${Assets.saladIngBase}17/5-ingredient.png",
      "${Assets.saladIngBase}17/6-ingredient.png",
    ],
    ingredientsNames: [
      "POTATOES",
      "YOGURT",
      "MAYONNAISE",
      "MUSTARD",
      "OLIVE OIL",
      "LEMON",
    ],
  ),
  FoodModel(
    foodType: "Salad",
    foodName: "Ohitashi",
    description:
        "Ohitashi is a traditional Japanese dish and a technique in which vegetables (and sometimes seafood) are boiled and immersed in a dashi-based sauce. Nowadays, the dish is usually prepared with spinach that's boiled, topped with dried bonito flakes (katsuoboshi), and dressed with soy sauce.",
    imagePath: "${Assets.saladBase}Ohitashi.jpg",
    foodPrice: 43.0,
    foodRate: 4.0,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    ingredientsImages: [
      "${Assets.saladIngBase}18/1-ingredient.png",
      "${Assets.saladIngBase}18/2-ingredient.png",
      "${Assets.saladIngBase}18/3-ingredient.png",
      "${Assets.saladIngBase}18/4-ingredient.png",
      "${Assets.saladIngBase}18/5-ingredient.png",
      "${Assets.saladIngBase}18/6-ingredient.png",
      "${Assets.saladIngBase}18/7-ingredient.png",
    ],
    ingredientsNames: [
      "SPINACH",
      "SALT",
      "KOMBU",
      "MIRIN",
      "SOY SAUCE",
      "SESAME SEEDS",
      "KATSUOBUSHI",
    ],
  ),
  FoodModel(
    foodType: "Salad",
    foodName: "Zaalouk",
    description:
        "Zaalouk is a traditional Moroccan salad made by cooking eggplant, tomatoes, garlic, and flavorings such as cumin, paprika, coriander, and parsley. Although it can be served on its own, zaalouk is also often served as a side dish, a spread for sandwiches, or a dip, when it is paired with crusty bread.",
    imagePath: "${Assets.saladBase}Zaalouk.jpg",
    foodPrice: 77.0,
    foodRate: 4.1,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    ingredientsImages: [
      "${Assets.saladIngBase}19/1-ingredient.png",
      "${Assets.saladIngBase}19/2-ingredient.png",
      "${Assets.saladIngBase}19/3-ingredient.png",
      "${Assets.saladIngBase}19/4-ingredient.png",
      "${Assets.saladIngBase}19/5-ingredient.png",
      "${Assets.saladIngBase}19/6-ingredient.png",
      "${Assets.saladIngBase}19/7-ingredient.png",
    ],
    ingredientsNames: [
      "EGGPLANT",
      "TOMATO",
      "GARLIC",
      "CUMIN",
      "PAPRIKA",
      "CORIANDER",
      "PARSLEY",
    ],
  ),
  FoodModel(
    foodType: "Salad",
    foodName: "Salată orientală",
    description:
        "Salată orientală is a simple Romanian potato salad consisting of boiled potatoes, onions, hard-boiled eggs, and olives, all seasoned and dressed with a combination of oil and vinegar. Versions of this salad call for the addition of mayonnaise, pickles, pickled red peppers or other vegetables, or the omission of vinegar.",
    imagePath: "${Assets.saladBase}Salată-orientală.jpg",
    foodPrice: 23.0,
    foodRate: 3.4,
    calories: RandomData.getRandomCalories,
    numberOfReviewers: RandomData.getRandomReviewers,
    ingredientsImages: [
      "${Assets.saladIngBase}20/1-ingredient.png",
      "${Assets.saladIngBase}20/2-ingredient.png",
      "${Assets.saladIngBase}20/3-ingredient.png",
      "${Assets.saladIngBase}20/4-ingredient.png",
      "${Assets.saladIngBase}20/5-ingredient.png",
    ],
    ingredientsNames: [
      "POTATOES",
      "ONION",
      "EGGS",
      "OLIVES",
      "PICKLING",
    ],
  ),
];
