import 'package:foodapp/constants/assets.dart';
import 'package:foodapp/data_layer/data_base/global_demo_data_model.dart';

List<FoodModel> vegetarianDishesDemoData = [
  FoodModel(
    foodType: "Vegetarian",
    foodName: "Hummus",
    description:
        "This internationally popular, beige-colored spread is traditionally made with mashed chickpeas, tahini sesame paste, lemon juice, and garlic. People across the world love hummus for its tangy flavor and the fact that it is filled with nutrients.",
    imagePath: "${Assets.vegBase}Hummus.jpg",
    foodPrice: 22.0,
    foodRate: 4.4,
    numberOfReviewers: 234,
    ingredientsNames: [
      "CHICKPEAS",
      "SESAME SEEDS",
      "LEMON JUICE",
      "GARLIC",
      "OLIVE OIL",
      "CUMIN",
      "SALT",
    ],
    ingredientsImages: [
      "${Assets.vegIngBase}1/1-ingredient.png",
      "${Assets.vegIngBase}1/2-ingredient.png",
      "${Assets.vegIngBase}1/3-ingredient.png",
      "${Assets.vegIngBase}1/4-ingredient.png",
      "${Assets.vegIngBase}1/5-ingredient.png",
      "${Assets.vegIngBase}1/6-ingredient.png",
      "${Assets.vegIngBase}1/7-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "Vegetarian",
    foodName: "Guacamole",
    description:
        "Guacamole is a world-famous buttery delicacy dating back all the way to the Aztec empire of the 1500s. It's a healthy blend of ripe, mashed avocados, onions, chiles, optional tomatillos and selected seasonings such as sea salt and coriander.",
    imagePath: "${Assets.vegBase}Guacamole.jpg",
    foodPrice: 232,
    foodRate: 4.1,
    numberOfReviewers: 235,
    ingredientsNames: [
      "AVOCADO",
      "LIME",
      "ONION",
      "Tlaola ",
      "CORIANDER",
      "SALT",
    ],
    ingredientsImages: [
      "${Assets.vegIngBase}2/1-ingredient.png",
      "${Assets.vegIngBase}2/2-ingredient.png",
      "${Assets.vegIngBase}2/3-ingredient.png",
      "${Assets.vegIngBase}2/4-ingredient.png",
      "${Assets.vegIngBase}2/5-ingredient.png",
      "${Assets.vegIngBase}2/6-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "Vegetarian",
    foodName: "Dal",
    description:
        "This flavorful and highly nutritious national dish of India is especially popular in southern parts of the country, but it can also be found in Nepal, Sri Lanka, Pakistan, and Bangladesh. Dal is a stew with the main ingredient of black or yellow lentils—the most consumed ingredients in India—but it can also be prepared with peas, chickpeas, or mung beans.",
    imagePath: "${Assets.vegBase}Dal.jpg",
    foodPrice: 34.3,
    foodRate: 3.0,
    numberOfReviewers: 3422,
    ingredientsNames: [
      "LENTILS",
      "PEAS",
      "MUNG BEAN",
      "CARAWAY",
      "CORIANDER",
      "ONION",
      "GARLIC",
      "TOMATO",
    ],
    ingredientsImages: [
      "${Assets.vegIngBase}3/1-ingredient.png",
      "${Assets.vegIngBase}3/2-ingredient.png",
      "${Assets.vegIngBase}3/3-ingredient.png",
      "${Assets.vegIngBase}3/4-ingredient.png",
      "${Assets.vegIngBase}3/5-ingredient.png",
      "${Assets.vegIngBase}3/6-ingredient.png",
      "${Assets.vegIngBase}3/7-ingredient.png",
      "${Assets.vegIngBase}3/8-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "Vegetarian",
    foodName: "Ratatouille",
    description:
        "This colorful Provençal vegetable ragout is traditionally made with simple, easily accessible ingredients: courgettes, eggplants, green and red peppers, tomatoes, onions, garlic, and parsley. The name ratatouille stems from the old Occitan word ratatolha, and the French word touiller, both meaning to toss, or to stir up, referring to the cooking process in which the ingredients are first simmered separately—seasoned with salt, pepper, and olive oil—and then tossed together and stirred into a vibrant vegetable medley.",
    imagePath: "${Assets.vegBase}Ratatouille.jpg",
    foodPrice: 22.11,
    foodRate: 3.2,
    numberOfReviewers: 220,
    ingredientsNames: [
      "ZUCCHINI",
      "EGGPLANT",
      "BELL PEPPER",
      "TOMATO",
      "ONION",
      "GARLIC",
      "PARSLEY",
      "OLIVE OIL",
    ],
    ingredientsImages: [
      "${Assets.vegIngBase}4/1-ingredient.png",
      "${Assets.vegIngBase}4/2-ingredient.png",
      "${Assets.vegIngBase}4/3-ingredient.png",
      "${Assets.vegIngBase}4/4-ingredient.png",
      "${Assets.vegIngBase}4/5-ingredient.png",
      "${Assets.vegIngBase}4/6-ingredient.png",
      "${Assets.vegIngBase}4/7-ingredient.png",
      "${Assets.vegIngBase}4/8-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "Vegetarian",
    foodName: "Kuku",
    description:
        "Kuku is the universal term for a broad group of Iranian dishes that resemble a thick omelet. Typically pan-fried, these dishes are predominately vegetarian, although some varieties occasionally employ meat. Some of the most famous varieties are kuku sabzi, which consists of eggs and various chopped herbs, and the potato-based kuku sib-zamini. Versatile kuku dishes are a staple in Iranian cuisine - they are often served on special occasions, but are also commonly prepared as simple everyday meals.",
    imagePath: "${Assets.vegBase}Kuku.jpg",
    foodPrice: 23.99,
    foodRate: 3.2,
    numberOfReviewers: 247,
    ingredientsNames: [
      "ZUCCHINI",
      "EGGPLANT",
      "BELL PEPPER",
      "TOMATO",
      "ONION",
      "GARLIC",
      "PARSLEY",
      "OLIVE OIL",
    ],
    ingredientsImages: [
      "${Assets.vegIngBase}5/1-ingredient.png",
      "${Assets.vegIngBase}5/2-ingredient.png",
      "${Assets.vegIngBase}5/3-ingredient.png",
      "${Assets.vegIngBase}5/4-ingredient.png",
      "${Assets.vegIngBase}5/5-ingredient.png",
      "${Assets.vegIngBase}5/6-ingredient.png",
      "${Assets.vegIngBase}5/7-ingredient.png",
      "${Assets.vegIngBase}5/8-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "Vegetarian",
    foodName: "Gazpacho",
    description:
        "A perfect remedy for a hot summer day called gazpacho is a cold soup consisting of crushed tomatoes, finely chopped cucumbers, onions, peppers, croutons, vinegar, and olive oil. With the same level of familiarity as paella to the consumers worldwide, the soup's refreshing, cool and acidic flavors promote Spanish cuisine at its best.",
    imagePath: "${Assets.vegBase}Gazpacho.jpg",
    foodPrice: 23.98,
    foodRate: 3.6,
    numberOfReviewers: 3451,
    ingredientsNames: [
      "BREAD",
      "TOMATO",
      "CUCUMBER",
      "ONION",
      "GARLIC",
      "PEPPERS",
      "SALT",
      "OLIVE OIL",
    ],
    ingredientsImages: [
      "${Assets.vegIngBase}6/1-ingredient.png",
      "${Assets.vegIngBase}6/2-ingredient.png",
      "${Assets.vegIngBase}6/3-ingredient.png",
      "${Assets.vegIngBase}6/4-ingredient.png",
      "${Assets.vegIngBase}6/5-ingredient.png",
      "${Assets.vegIngBase}6/6-ingredient.png",
      "${Assets.vegIngBase}6/7-ingredient.png",
      "${Assets.vegIngBase}6/8-ingredient.png",
    ],
  ),
  FoodModel(
    foodType: "Vegetarian",
    foodName: "Vinegret",
    description:
        "Originally invented in the 19th century, vinegret is the oldest, extremely popular Russian salad usually consisting of boiled beets, potatoes, and carrots combined with diced pickles, sauerkraut, and onions. The name of the salad is derived from the French term vinaigrette, which denotes an oily salad dressing in France.",
    imagePath: "${Assets.vegBase}Vinegret.jpg",
    foodPrice: 23.88,
    foodRate: 3.8,
    numberOfReviewers: 365,
    ingredientsNames: [
      "CHICKPEAS",
      "SESAME SEEDS",
      "LEMON JUICE",
      "GARLIC",
      "OLIVE OIL",
      "CUMIN",
      "SALT",
    ],
    ingredientsImages: [
      "${Assets.vegIngBase}7/1-ingredient.png",
      "${Assets.vegIngBase}7/2-ingredient.png",
      "${Assets.vegIngBase}7/3-ingredient.png",
      "${Assets.vegIngBase}7/4-ingredient.png",
      "${Assets.vegIngBase}7/5-ingredient.png",
      "${Assets.vegIngBase}7/6-ingredient.png",
      "${Assets.vegIngBase}7/7-ingredient.png",
    ],
  ),
];
